### PR TITLE
Implements parameterize_extract_columns + a dataframe API

### PR DESCRIPTION
**Pull request by elijahbenizzy**
This provides a convenience API for
https://github.com/stitchfix/hamilton/issues/196. The idea is that people want to do a parameterization and extract columns operator at once -- this should be easy. The cool thing is that this just uses the parameterize and extract APIs. It also has a from_df() function to allow for passing in a dataframe to be more concise.

[Short description explaining the high-level reason for the pull request]

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by ropeladder** [comment]
This is failing for me here:
https://github.com/stitchfix/hamilton/blob/parameterized_extract/hamilton/function_modifiers/expanders.py#L659
(`df` is undefined)

I'm just using code that worked with the parameterized_frame branch so I may have missed some changes for this release, but on the other hand it does look like `df` isn't getting defined.

**Comment by elijahbenizzy** [comment]
> This is failing for me here: https://github.com/stitchfix/hamilton/blob/parameterized_extract/hamilton/function_modifiers/expanders.py#L659 (`df` is undefined)
> 
> I'm just using code that worked with the parameterized_frame branch so I may have missed some changes for this release, but on the other hand it does look like `df` isn't getting defined.

Hey -- I'm really sorry about this, and the delay in responding. Did a last minute change to the parameter names and didn't get it right :/ 

On the plus side I anticipate having a lot more time to focus on OS stuff soon -- will be around to fix any more bugs! Will be adding more tests shortly as well :)

**Comment by elijahbenizzy** [comment]
Realized I didn't tag you @ropeladder -- feel free to reach out if you have any more Qs!

**Comment by elijahbenizzy** [comment]
OK I'm simplifying PRs -- merging this one into the other branch.

**Pull request merged**
