### PR TITLE
remove unused imports

### PR DESCRIPTION
**Pull request by jameslamb**
Thanks for this great project! I learned about Hamilton recently and was interested in contributing.

I noticed this project isn't currently using `flake8`, so I ran that over the code in this repo to look for opportunities to fix minor things.

This PR proposes removing a few unused imports found by running `flake8 .` from the root of the repo.

```text
./examples/model_examples/scikit-learn/my_train_evaluate_logic.py:1:1: F401 'typing.List' imported but unused
./examples/ray/hello_world/run.py:3:1: F401 'sys' imported but unused
./examples/ray/hello_world/run.py:5:1: F401 'pandas as pd' imported but unused
./examples/spark/hello_world/run.py:3:1: F401 'sys' imported but unused
./graph_adapter_tests/h_dask/test_h_dask.py:1:1: F401 'numpy as np' imported but unused
./hamilton/node.py:1:1: F401 'copy' imported but unused
```

## Additions

--

## Removals

Removes unused imports.

## Testing

--

## Screenshots

--

## Notes

--

## Todos

--

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [TODO link to standards]()
- [ ] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

--

### Python

- [ ] python 3.6
- [ ] python 3.7

### Notes for Reviewers

I tried to follow the PR template, but I don't understand what the "Python" section means.

Thanks very much for your time and consideration!

### CODE REVIEW

**Comment by elijahbenizzy** [comment]
Looks good to me! Thanks so much for contributing. Pretty sure it works but I want to run the automated tests -- will do so shortly. I think this would be great to add as an integration test (E.G. that flake8 never fails), but first we need to do this: https://github.com/stitchfix/hamilton/issues/77, so I think this is a good start!

**Comment by skrawcz** [comment]
Side note: I would love to move to black -- but am afraid of losing all the commit history... :/

**Comment by jameslamb** [comment]
Thanks very much!

> I think this would be great to add as an integration test (E.G. that flake8 never fails)

I'd be happy to do that work (in small PRs, one type of `flake8` warning at a time) if you all are interested!

> but first we need to do this: https://github.com/stitchfix/hamilton/issues/77

I agree, #77 would be an important step towards improving the contributor experience here, and would reduce the effort required by maintainers.

**Comment by elijahbenizzy** [comment]
Tests pass! Pushed to a clone of this branch and it worked :) We'll work on #77 so its easier to add automated tests.

**Review by elijahbenizzy — APPROVED** [review]

**Comment by elijahbenizzy** [comment]
Also I added you as a contributor, to me merged once you merge this one :) https://github.com/stitchfix/hamilton/pull/78 (still figuring out security settings so I put @skrawcz as the reviewer on that, just want your approval to list your name).

**Pull request merged**
