### PR TITLE
Uses the base python graph adapter for type-checking in experimental

### PR DESCRIPTION
**Pull request by elijahbenizzy**
graph adapters

Before we were doing it in a custom way -- this broke when a user wanted to use generics. We still don't have amazing generic/type comparison, but this should be able to clean it up.

[Short description explaining the high-level reason for the pull request]

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by elijahbenizzy** [comment]
Worth testing? Probably only with integration tests -- all the functionality is unit-tested.

**Comment by skrawcz** [comment]
This may or may not be the right approach.

What we really need is a test case to reproduce the issue that was seen :)

**Comment by elijahbenizzy** [comment]
Yeah this was a quick educated guess. IMO this is the right thing to do, we just need to validate that it's the best way to solve the problem. IMO inheritance is a little cleaner for this sort of thing too...

**Comment by skrawcz** [comment]
> Yeah this was a quick educated guess. IMO this is the right thing to do, we just need to validate that it's the best way to solve the problem. Inheritance is probably a little cleaner for this sort of thing too...

Actually yeah I think that should work. The point is that these adapters should fudge whatever types they need to, but otherwise delegating to super feels right overall for them.

**Review by skrawcz — APPROVED** [review]

**Review by skrawcz — APPROVED** [review]

**Pull request merged**
