### PR TITLE
adding build via poetry

### PR DESCRIPTION
**Pull request by AdityaSoni19031997**
The PR intends to use poetry going ahead for building hamilton!

## Additions

- Attempt to fix the issue mentioned here https://github.com/stitchfix/hamilton/issues/12.

## Removals

- NA

## Changes

- Have added the `pyproject.toml` file and the corresponding `poetry.lock` files and verified that the test are running properly.

## Testing

1. Have ran the test suite that's available on the repo via pytest.

## Screenshots
If applicable

Screenshot 2021-11-13 at 2 23 19 PM

## Notes

- The **dynamic versioning** is not possible in poetry as of now without adding another plugin to the same or work arounds.
- The latest version of **Pandas** has a minimum Python version requirement of **3.7.1+** as per [PyPi](https://pypi.org/project/pandas/).

## Todos

- Didn't verify **circle-ci** coverage.
- Figure out the dynamic versioning fix.

## Checklist

- [✔️] PR has an informative and human-readable title
- [✔️] Changes are limited to a single goal (no scope creep)
- [✔️] Code can be automatically merged (no conflicts)
- [✔️] Code follows the standards laid out in the [TODO link to standards]()
- [✔️] Passes all existing automated tests
- [] Any _change_ in functionality is tested
- [] New functions are documented (with a description, list of inputs, and expected output)
- [] Placeholder code is flagged / future todos are captured in comments
- [] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist
- Executed the pytest test_suite. 

### Python

- [] python 3.6
- [] python 3.7
- [✔️] python 3.7.1+

### CODE REVIEW

**Comment by AdityaSoni19031997** [comment]
cc @skrawcz; Please let me know your suggestions and possible improvements on the same.

**Comment by AdityaSoni19031997** [comment]
cc @skrawcz; Please let me know your suggestions and possible improvements on the same.

**Comment by skrawcz** [comment]
@AdityaSoni19031997 can you explain the rationale for choosing poetry over other options please?

**Comment by AdityaSoni19031997** [comment]
Well, TBH, i would stick to use `setup.py`, `venv` etc itself because it's very widely adopted as of now. So lot of help can be received! Plus, you can do custom stuffs there as well by following the docs or some other public repos. 

Poetry is nice and is currently being adopted slowly by people as well but it still is yet to stand the test of time because of 1k+ open issues on it and very less contributors. To do custom things here, It's gonna be a little more trickier for sure. If a repo updates itself or it's reqs are not mentioned properly, poetry can help there by updating or figuring out the correct compatible versions of the modules. Plus, we can also specify our own custom build script in 
poetry as well under `[tool.poetry.build]`, that's all! Plus wanted to try it for a real project as well, hence tried it. That's all.

What other options do you have on your mind?

Best,
Aditya.

**Comment by skrawcz** [comment]
@AdityaSoni19031997 thanks for the PR.

Yeah I'm not too familiar with poetry. There are many options, and after taking a quick look I think I'd want to stick with setuptools for this project. Mainly because we don't use poetry here at Stitch Fix, and setuptools uses pip, which poetry does not.

**Comment by AdityaSoni19031997** [comment]
Thanks for getting back! Maybe in future one can look to migrate to Poetry! Will close the PR then;

Best,
Aditya.

**Pull request closed without merging**
